info:
  build:
    name: call_centre_manager-api
    version: 1.0.0

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: ccm

  datasource:
    url: jdbc:postgresql://localhost:5432/db?currentSchema=ccm
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
