create schema ccm;

drop table if exists ccm.team;
create table ccm.team (
   teamid bigint generated by default as identity (start with 1) NOT NULL PRIMARY KEY,
   name  varchar(50)
);

insert into ccm.team (name) values ( 'Paris Saint Germain');
insert into ccm.team (name) values ( 'FC Bayern Munich');
